export const title =
  "Chose from 185,000 online video courses with new additions published every month";
export const description =
  "Take one of Udemy’s range of Python courses and learn how to code using this incredibly useful language. Its simple syntax and readability makes Python perfect for Flask, Django, data science, and machine learning. You’ll learn how to build everything from games to sites to apps. Choose from a range of courses that will appeal to...";

export const courses = [
  {
    id: "1",
    title: "The Python and Django Learning Guide",
    author: "Hassan Fulaih",
    image: "https://img-b.udemycdn.com/course/240x135/2426532_a277_7.jpg",
    rate: 3,
    ratersCount: 3430,
    newPrice: 49.99,
    oldPrice: 99.99,
  },
  {
    id: "2",
    title: "Python For Beginners [in Arabic]",
    author: "Hassan Fulaih",
    image: "https://img-b.udemycdn.com/course/240x135/4230080_0693.jpg",
    rate: 2,
    ratersCount: 1041,
    newPrice: 39.99,
    oldPrice: 59.99,
  },
  {
    id: "3",
    title: "Python For Beginners [in Arabic]",
    author: "Hassan Fulaih",
    image: "https://img-b.udemycdn.com/course/240x135/4434202_3db6.jpg",
    rate: 3,
    ratersCount: 1041,
    newPrice: 39.99,
    oldPrice: 59.99,
  },
  {
    id: "4",
    title: "Python For Beginners [in Arabic]",
    author: "Hassan Fulaih",
    image: "https://img-b.udemycdn.com/course/240x135/4455448_6e62_4.jpg",
    rate: 3.5,
    ratersCount: 2041,
    newPrice: 19.99,
    oldPrice: 69.99,
  },
  {
    id: "5",
    title: "The Complete Programming Fundamentals Course",
    author: "Hassan Fulaih",
    image: "https://img-b.udemycdn.com/course/240x135/4226056_5e40_3.jpg",
    rate: 4,
    ratersCount: 4041,
    newPrice: 99.99,
    oldPrice: 149.99,
  },
  {
    id: "6",
    title: "Python For Beginners [in Arabic]",
    author: "Hassan Fulaih",
    image: "https://img-b.udemycdn.com/course/240x135/4434202_3db6.jpg",
    rate: 3,
    ratersCount: 1041,
    newPrice: 39.99,
    oldPrice: 59.99,
  },
  {
    id: "7",
    title: "Python For Beginners [in Arabic]",
    author: "Hassan Fulaih",
    image: "https://img-b.udemycdn.com/course/240x135/4455448_6e62_4.jpg",
    rate: 3.5,
    ratersCount: 2041,
    newPrice: 19.99,
    oldPrice: 69.99,
  },
];
